# Generated by Django 5.2.6 on 2025-10-03 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0004_remove_userskillstats_uq_userskillstats_enrollment_skill_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('correct_answers', models.IntegerField(default=0)),
                ('incorrect_answers', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('perfect_lesson', models.BooleanField(default=False, help_text='Không sai câu nào')),
                ('speed_bonus', models.IntegerField(default=0)),
                ('combo_bonus', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('answers_data', models.JSONField(blank=True, default=dict, help_text='Chi tiết từng câu trả lời')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sessions', to='languages.languageenrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='languages.lesson')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='learning_le_user_id_963cb0_idx'), models.Index(fields=['enrollment', 'status'], name='learning_le_enrollm_baca6a_idx'), models.Index(fields=['lesson', 'completed_at'], name='learning_le_lesson__ca1bd5_idx'), models.Index(fields=['status', 'last_activity'], name='learning_le_status_f02bf1_idx')],
            },
        ),
    ]
