# Generated by Django 5.2.7 on 2025-10-17 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['user', 'started_at'], name='learning_le_user_id_963cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['enrollment', 'status'], name='learning_le_enrollm_baca6a_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['lesson', 'completed_at'], name='learning_le_lesson__ca1bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['status', 'last_activity'], name='learning_le_status_f02bf1_idx'),
        ),
    ]
