# Generated by Django 5.2.7 on 2025-10-22 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_topicprogress_highest_completed_order'),
        ('learning', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=64)),
                ('is_correct', models.BooleanField(default=False)),
                ('user_answer', models.TextField(blank=True)),
                ('expected', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.lessonsession')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.skill')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'created_at'], name='learning_se_session_d2d4d2_idx'), models.Index(fields=['skill', 'created_at'], name='learning_se_skill_i_781c2b_idx')],
            },
        ),
    ]
