# Generated by Django 5.2.7 on 2025-11-12 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0010_matchingpair_left_text_i18n_skill_description_i18n_and_more'),
        ('learning', '0003_sessionanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('attempts_count', models.IntegerField(default=0)),
                ('best_score', models.FloatField(default=0.0)),
                ('avg_score', models.FloatField(default=0.0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_sessions', to='languages.languageenrollment')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_sessions', to='languages.lesson')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='languages.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PronAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_text', models.TextField(blank=True, default='')),
                ('recognized', models.TextField(blank=True, default='')),
                ('score_overall', models.FloatField(default=0.0)),
                ('words', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('audio_path', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.pronunciationprompt')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.skillsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='skillsession',
            index=models.Index(fields=['user', 'started_at'], name='learning_sk_user_id_9a144c_idx'),
        ),
        migrations.AddIndex(
            model_name='skillsession',
            index=models.Index(fields=['enrollment', 'status'], name='learning_sk_enrollm_487545_idx'),
        ),
        migrations.AddIndex(
            model_name='skillsession',
            index=models.Index(fields=['skill', 'last_activity'], name='learning_sk_skill_i_21347e_idx'),
        ),
        migrations.AddIndex(
            model_name='pronattempt',
            index=models.Index(fields=['session', 'created_at'], name='learning_pr_session_10e0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='pronattempt',
            index=models.Index(fields=['score_overall'], name='learning_pr_score_o_e261de_idx'),
        ),
    ]
