# Generated by Django 5.2.7 on 2025-11-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_skillsession_pronattempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsession',
            name='session_id',
        ),
    ]
