# Generated by Django 5.2.7 on 2025-11-03 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0010_matchingpair_left_text_i18n_skill_description_i18n_and_more'),
        ('social', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboardentry',
            options={'ordering': ['-date', 'rank']},
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['language', 'date', '-xp'], name='idx_lb_lang_date_xp_desc'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['language', 'date', 'rank'], name='idx_lb_lang_date_rank'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['user', 'date'], name='idx_lb_user_date'),
        ),
    ]
