# Generated by Django 5.2.6 on 2025-10-03 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friend',
            name='unique_friendship',
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['from_user', 'to_user', 'accepted'], name='social_frie_from_us_203ec7_idx'),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='uq_friend_from_to'),
        ),
    ]
