# Generated by Django 5.2.7 on 2025-11-08 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_leaderboardentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('event_reminder', 'Event Reminder'), ('quest_update', 'Quest Update'), ('league_reset', 'League Reset'), ('streak_alert', 'Streak Alert'), ('system', 'System')], default='system', max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='kind',
            field=models.CharField(choices=[('personal', 'Personal'), ('daily_goal', 'Daily Goal'), ('weekly_goal', 'Weekly Goal'), ('xp_boost', 'XP Boost'), ('duel', 'Friend Duel'), ('study_group', 'Study Group'), ('friend_quest', 'Friend Quest'), ('system', 'System')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='event_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='remind_before_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='rrule',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'start'], name='social_cale_user_id_ab520a_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['kind', 'start'], name='social_cale_kind_528e1b_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.badge'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='social_noti_user_id_b17210_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at'], name='social_noti_user_id_26a73a_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user', 'awarded_at'], name='social_user_user_id_c3020c_idx'),
        ),
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('user', 'badge'), name='uq_userbadge_user_badge'),
        ),
    ]
