"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab
from datetime import timedelta
import os
from utils.config_log import LOGGING as DJANGO_LOGGING

try:
    from dotenv import load_dotenv  # type: ignore
except Exception:
    load_dotenv = None  # fallback if python-dotenv is not installed

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
if load_dotenv:
    try:
        load_dotenv(BASE_DIR.parent / ".env")
    except Exception:
        pass

LOGGING = DJANGO_LOGGING

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'dev-secret')

DEBUG = True

allowed_hosts_env = os.getenv('DJANGO_ALLOWED_HOSTS')
ALLOWED_HOSTS = allowed_hosts_env.split(',') if allowed_hosts_env else []

AUTH_USER_MODEL = 'users.User'
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

CORS_ALLOW_ALL_ORIGINS = True


CORS_ALLOW_CREDENTIALS = False
CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'ngrok-skip-browser-warning',
]

# (Tuỳ chọn) Cho phép các method
from corsheaders.defaults import default_headers
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",      
    "http://127.0.0.1:5173",
    "https://ai-l-languages-fe-dfyo.vercel.app",
    "https://ai-l-languages-fe-5vkw.vercel.app",
    "https://ai-l-languages-fe-pr4t.vercel.app",
    "https://ai-l-languages-fe.vercel.app",
    
]
#  CSRF (SessionAuth), cần tin tưởng origin FE:
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://ai-l-languages-fe-dfyo.vercel.app",
    "https://ai-l-languages-fe-5vkw.vercel.app",
    "https://ai-l-languages-fe-pr4t.vercel.app",
    "https://d5e6478e8939.ngrok-free.app", 
    "https://ai-l-languages-fe.vercel.app",
]


SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_SAMESITE = "Lax"   # nếu FE khác domain → dùng "None"
SESSION_COOKIE_SECURE = False     # PROD: True
CSRF_COOKIE_SAMESITE   = "Lax"    # nếu FE khác domain → "None"
CSRF_COOKIE_SECURE     = False    # PROD: True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'social',
    'languages',
    'vocabulary',
    'learning',
    'progress',
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'chat',
    'speech',
    "recommend",
    "corsheaders",
    "channels",
    "pgvector.django",
    "django_filters",
]

MIDDLEWARE = [
     'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware", 
    'utils.middleware.RequestIDMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'

DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'be_db',
        'USER': 'postgres',
        'PASSWORD': 'portgasDace',
        'HOST': '127.0.0.1', 
        'PORT': '5543',    
    }
}

REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
REDIS_DB   = os.getenv("REDIS_DB", "0")
REDIS_URL  = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)         # redis://localhost:6379/0
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL) # redis://localhost:6379/0
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh' 
USE_TZ = True 
CELERY_BEAT_SCHEDULE = {
    'update-daily-leaderboard-every-30-mins': {
        'task': 'social.update_daily_leaderboard',
        'schedule': crontab(minute='*/3'),  # Chạy mỗi 30 phút
    },
}     

ASGI_APPLICATION = "server.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        # "BACKEND": "channels.layers.InMemoryChannelLayer",
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        # chấp nhận cả URL hoặc (host, port)
        "CONFIG": {"hosts": [REDIS_URL]},  # hoặc [("localhost", 6379)]
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Auth
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

    # Pagination
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "PAGE_SIZE": 20,

    # Schema
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",

    # Renderers: dùng JSONRenderer cho API, Browsable để debug (tùy chọn).
    # KHÔNG dùng JSONOpenAPIRenderer làm renderer mặc định cho toàn bộ API.
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
        # "rest_framework.renderers.BrowsableAPIRenderer",  # bật khi dev
    ),
}

def assign_tag_from_second_segment(result, generator, request, public):
    """
    Gán tag cho từng operation theo segment thứ 2 sau '/api/'.
    Ví dụ:
      /api/daily-xp/                 -> "daily-xp"
      /api/topic-skill/lessons/      -> "topic-skill"
      /users/login/                  -> "users" (không có /api/ ở đầu)
    """
    paths = result.get("paths") or {}
    for path, methods in paths.items():
        # tách path thành segment
        segs = [s for s in path.strip("/").split("/") if s]
        if not segs:
            continue
        # nếu có 'api' ở đầu thì lấy segs[1], ngược lại lấy segs[0]
        if segs[0].lower() == "api":
            seg = segs[1] if len(segs) > 1 else "default"
        else:
            seg = segs[0]

        # GHI ĐÈ tag cho tất cả method hợp lệ
        for method, op in methods.items():
            if method.lower() in ("get", "post", "put", "patch", "delete", "options", "head"):
                op["tags"] = [seg] 
    return result


SPECTACULAR_SETTINGS = {
    'TITLE': 'BE API',
    'DESCRIPTION': 'API documentation for DATN project',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True, 
    'POSTPROCESSING_HOOKS': [
        'server.settings.assign_tag_from_second_segment',
    ],

}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),   
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),   
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}

# RAG config
RAG_INDEX_DIR = BASE_DIR / "var/rag_index"
RAG_TOP_K = 5
RAG_EMBED_BACKEND = os.getenv("RAG_EMBED_BACKEND", "st")  # 'st' | 'ollama'
RAG_ST_MODEL = os.getenv("RAG_ST_MODEL", "sentence-transformers/all-MiniLM-L6-v2")
RAG_OLLAMA_URL = os.getenv("RAG_OLLAMA_URL", "http://localhost:11435")
RAG_OLLAMA_EMBED_MODEL = os.getenv("RAG_OLLAMA_EMBED_MODEL", "nomic-embed-text:latest")
RAG_SCORE_THRESH = 0.25

MEDIA_URL = "/media/"   
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


INTERNAL_API_KEY = os.getenv("INTERNAL_API_KEY", "") 

PIPER_BIN = os.environ.get("PIPER_BIN", "piper") 
PIPER_TMP_DIR = r"D:\AI_LL\tmp"
PIPER_VOICE_DIR = os.environ.get("PIPER_VOICE_DIR", os.path.join(BASE_DIR, "voices"))
PIPER_VOICES = {
    # map ngôn ngữ L2 → file giọng .onnx/.onnx.json trong PIPER_VOICE_DIR
    "en": "en_US-amy-medium.onnx",
    "vi": "vi_VN-25hours_single-low.onnx",
    "zh": "zh_CN-huayan-medium.onnx",
}



