# Generated by Django 5.2.7 on 2025-10-17 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyxp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_xp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyxp',
            index=models.Index(fields=['user', 'date'], name='progress_da_user_id_e3aec1_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyxp',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uq_dailyxp_user_date'),
        ),
    ]
