# Generated by Django 5.2.6 on 2025-10-03 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyxp',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='dailyxp',
            index=models.Index(fields=['user', 'date'], name='progress_da_user_id_e3aec1_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyxp',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uq_dailyxp_user_date'),
        ),
    ]
