# Generated by Django 5.2.7 on 2025-11-08 11:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=20)),
                ('source_id', models.CharField(max_length=64)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'source_type', 'source_id'], name='progress_xp_user_id_4c9b8d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'source_type', 'source_id'), name='uq_xpevent_user_source_unique')],
            },
        ),
    ]
