# Generated by Django 5.2.7 on 2025-11-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_refresh_jti',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
