# Generated by Django 5.2.6 on 2025-10-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountswitch',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='accountswitch',
            constraint=models.UniqueConstraint(fields=('owner', 'alias'), name='uq_accountswitch_owner_alias'),
        ),
    ]
