# Generated by Django 5.2.6 on 2025-09-28 14:47

import utils.gencode
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accountsetting_accountswitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_code',
            field=models.CharField(blank=True, default=utils.gencode.generate_verify_code, max_length=6, null=True),
        ),
    ]
