"""
Django settings for ai project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from celery.schedules import crontab
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(Path(r"D:\AI_LL\.env"), override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'dev-secret')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
CORS_ALLOW_ALL_ORIGINS = True


CORS_ALLOW_CREDENTIALS = False
CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'ngrok-skip-browser-warning',
]

# (Tuỳ chọn) Cho phép các method
from corsheaders.defaults import default_headers
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",      
    "http://127.0.0.1:5173",
    "https://ai-l-languages-fe-dfyo.vercel.app",
    "https://ai-l-languages-fe-5vkw.vercel.app",
    "https://ai-l-languages-fe-pr4t.vercel.app",
    "https://ai-l-languages-fe.vercel.app",
    
]
#  CSRF (SessionAuth), cần tin tưởng origin FE:
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://ai-l-languages-fe-dfyo.vercel.app",
    "https://ai-l-languages-fe-5vkw.vercel.app",
    "https://ai-l-languages-fe-pr4t.vercel.app",
    "https://d5e6478e8939.ngrok-free.app", 
    "https://ai-l-languages-fe.vercel.app",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ai_recommend',
    "rest_framework",
    "drf_spectacular",
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ai_db',
        'USER': 'postgres',
        'PASSWORD': 'portgasDace',
        'HOST': 'localhost',
        'PORT': '5544',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        "ai_recommend.auth.authentication.BEJWTAuthentication",
        'rest_framework_simplejwt.authentication.JWTAuthentication',   
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        "rest_framework.renderers.JSONOpenAPIRenderer", 
        # Nếu cần thêm hỗ trợ khác (ví dụ UI), thêm vào đây
        # "rest_framework.renderers.BrowsableAPIRenderer",
        # "rest_framework.renderers.CoreJSONRenderer",
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'AI API',
    'DESCRIPTION': 'API documentation for DATN project',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True, 

}

CELERY_BROKER_URL = "redis://localhost:6379/1"
CELERY_RESULT_BACKEND = "redis://localhost:6379/1"
CELERY_TIMEZONE = "Asia/Ho_Chi_Minh"
CELERY_ENABLE_UTC = False

CELERY_BEAT_SCHEDULE = {
    "train-ai-model-every-10m": {
        "task": "ai.tasks.train_ai_model_task",
        "schedule": crontab(minute="*/60"),
        "options": {
            "queue": "ai",        # nếu bạn tách queue
            "expires": 8 * 60,    # job quá hạn sau 9 phút (tránh dồn đống)
        },
    },
}



# RAG config
RAG_INDEX_DIR = BASE_DIR / "var/rag_index"
RAG_TOP_K = 5
RAG_EMBED_BACKEND = os.getenv("RAG_EMBED_BACKEND", "st")  # 'st' | 'ollama'
RAG_ST_MODEL = os.getenv("RAG_ST_MODEL", "sentence-transformers/all-MiniLM-L6-v2")
RAG_OLLAMA_URL = os.getenv("RAG_OLLAMA_URL", "http://localhost:11435")
RAG_OLLAMA_EMBED_MODEL = os.getenv("RAG_OLLAMA_EMBED_MODEL", "nomic-embed-text:latest")


# BE_API_BASE_URL = "https://a43ded5eef5d.ngrok-free.app"
BE_API_BASE_URL = "http://localhost:8000"
BE_API_TOKEN="xxx"
BE_API_KEY="YYY"

BE_JWT_USERNAME = os.getenv("BE_JWT_USERNAME", "admin01")
BE_JWT_PASSWORD = os.getenv("BE_JWT_PASSWORD", "string1234")
BE_JWT_TOKEN_URL = os.getenv("BE_JWT_TOKEN_URL", "/api/users/login/")
BE_JWT_REFRESH_URL = os.getenv("BE_JWT_REFRESH_URL", "/api/users/login/")


from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),   
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),   
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}

MINIO_ENDPOINT   = os.getenv("MINIO_ENDPOINT")
MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY")
MINIO_BUCKET     = os.getenv("MINIO_BUCKET", "ai-snapshots")
MODEL_DIR        = BASE_DIR / "models"

