# Generated by Django 5.2.7 on 2025-10-17 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start_lesson', 'Start Lesson'), ('complete_lesson', 'Complete Lesson'), ('review_word', 'Review Word'), ('practice_skill', 'Practice Skill')], max_length=50)),
                ('value', models.FloatField(blank=True, help_text='điểm số/tỉ lệ đúng nếu có', null=True)),
                ('success', models.BooleanField(default=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_interactions', to='languages.languageenrollment')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.lesson')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('normalized', models.CharField(blank=True, max_length=200)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='languages.language')),
            ],
        ),
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('pronunciation', 'Pronunciation'), ('grammar', 'Grammar'), ('vocab', 'Vocabulary'), ('listening', 'Listening'), ('spelling', 'Spelling'), ('other', 'Other')], default='grammar', max_length=20)),
                ('prompt', models.TextField()),
                ('expected', models.TextField(blank=True, null=True)),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('mispronounced_words', models.JSONField(blank=True, null=True)),
                ('error_detail', models.JSONField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='languages.languageenrollment')),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistakes', to='vocabulary.learninginteraction')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.word')),
            ],
        ),
        migrations.AddField(
            model_name='learninginteraction',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.word'),
        ),
        migrations.CreateModel(
            name='KnownWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('ease_factor', models.FloatField(default=2.5, help_text='Ease factor (2.5 is default)')),
                ('interval_days', models.IntegerField(default=1, help_text='Days until next review')),
                ('repetitions', models.IntegerField(default=0, help_text='Number of successful repetitions')),
                ('next_review', models.DateTimeField(blank=True, help_text='When to review next', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='new', max_length=20)),
                ('total_reviews', models.IntegerField(default=0)),
                ('correct_reviews', models.IntegerField(default=0)),
                ('times_forgotten', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_words', to='languages.languageenrollment')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True, max_length=50)),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vocabulary.word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='vocabulary.word')),
            ],
        ),
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_assets', to='languages.language')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('language', 'key'), name='uq_audioasset_language_key')],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('example', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations_out', to='languages.language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations_in', to='languages.language')),
            ],
            options={
                'indexes': [models.Index(fields=['source_language', 'target_language'], name='vocabulary__source__0bc0fd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['language', 'text'], name='vocabulary__languag_d20e62_idx'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('language', 'text'), name='uq_word_language_text'),
        ),
        migrations.AddIndex(
            model_name='mistake',
            index=models.Index(fields=['user', 'timestamp'], name='vocabulary__user_id_5beee4_idx'),
        ),
        migrations.AddIndex(
            model_name='mistake',
            index=models.Index(fields=['enrollment', 'timestamp'], name='vocabulary__enrollm_bc4e36_idx'),
        ),
        migrations.AddIndex(
            model_name='mistake',
            index=models.Index(fields=['source'], name='vocabulary__source_65fe68_idx'),
        ),
        migrations.AddIndex(
            model_name='learninginteraction',
            index=models.Index(fields=['user', 'created_at'], name='vocabulary__user_id_98c8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='learninginteraction',
            index=models.Index(fields=['enrollment', 'created_at'], name='vocabulary__enrollm_31c282_idx'),
        ),
        migrations.AddIndex(
            model_name='learninginteraction',
            index=models.Index(fields=['skill', 'created_at'], name='vocabulary__skill_i_5c116c_idx'),
        ),
        migrations.AddIndex(
            model_name='learninginteraction',
            index=models.Index(fields=['lesson', 'created_at'], name='vocabulary__lesson__65ec0f_idx'),
        ),
        migrations.AddIndex(
            model_name='learninginteraction',
            index=models.Index(fields=['action'], name='vocabulary__action_d9bdd4_idx'),
        ),
        migrations.AddIndex(
            model_name='knownword',
            index=models.Index(fields=['enrollment', 'next_review'], name='vocabulary__enrollm_f6d89c_idx'),
        ),
        migrations.AddIndex(
            model_name='knownword',
            index=models.Index(fields=['enrollment', 'status'], name='vocabulary__enrollm_bab3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='knownword',
            index=models.Index(fields=['next_review'], name='vocabulary__next_re_74bbc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='knownword',
            constraint=models.UniqueConstraint(fields=('enrollment', 'word'), name='uq_knownword_enrollment_word_v2'),
        ),
        migrations.AddIndex(
            model_name='wordrelation',
            index=models.Index(fields=['relation_type'], name='vocabulary__relatio_c41727_idx'),
        ),
        migrations.AddConstraint(
            model_name='wordrelation',
            constraint=models.UniqueConstraint(fields=('word', 'related', 'relation_type'), name='uq_wordrelation_word_related_type'),
        ),
    ]
