# Generated by Django 5.2.6 on 2025-10-03 20:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_alter_suggestedlesson_unique_together_and_more'),
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start_lesson', 'Start Lesson'), ('complete_lesson', 'Complete Lesson'), ('review_word', 'Review Word'), ('practice_skill', 'Practice Skill')], max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('pronunciation', 'Pronunciation'), ('grammar', 'Grammar'), ('vocab', 'Vocabulary'), ('listening', 'Listening'), ('spelling', 'Spelling')], default='grammar', max_length=20)),
                ('prompt', models.TextField()),
                ('expected', models.TextField(blank=True, null=True)),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('mispronounced_words', models.JSONField(blank=True, null=True)),
                ('error_detail', models.JSONField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='audioasset',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='knownword',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wordrelation',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='knownword',
            index=models.Index(fields=['enrollment', 'score'], name='vocabulary__enrollm_3ee234_idx'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['source_language', 'target_language'], name='vocabulary__source__0bc0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['language', 'text'], name='vocabulary__languag_d20e62_idx'),
        ),
        migrations.AddIndex(
            model_name='wordrelation',
            index=models.Index(fields=['relation_type'], name='vocabulary__relatio_c41727_idx'),
        ),
        migrations.AddConstraint(
            model_name='audioasset',
            constraint=models.UniqueConstraint(fields=('language', 'key'), name='uq_audioasset_language_key'),
        ),
        migrations.AddConstraint(
            model_name='knownword',
            constraint=models.UniqueConstraint(fields=('enrollment', 'word'), name='uq_knownword_enrollment_word'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('language', 'text'), name='uq_word_language_text'),
        ),
        migrations.AddConstraint(
            model_name='wordrelation',
            constraint=models.UniqueConstraint(fields=('word', 'related', 'relation_type'), name='uq_wordrelation_word_related_type'),
        ),
        migrations.AddField(
            model_name='learninginteraction',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_interactions', to='languages.languageenrollment'),
        ),
        migrations.AddField(
            model_name='learninginteraction',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.lesson'),
        ),
        migrations.AddField(
            model_name='learninginteraction',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.skill'),
        ),
        migrations.AddField(
            model_name='learninginteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mistake',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='languages.languageenrollment'),
        ),
        migrations.AddField(
            model_name='mistake',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistakes', to='vocabulary.learninginteraction'),
        ),
        migrations.AddField(
            model_name='mistake',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.lesson'),
        ),
        migrations.AddField(
            model_name='mistake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mistake',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.word'),
        ),
        migrations.AddIndex(
            model_name='learninginteraction',
            index=models.Index(fields=['user', 'created_at'], name='vocabulary__user_id_98c8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='mistake',
            index=models.Index(fields=['user', 'timestamp'], name='vocabulary__user_id_5beee4_idx'),
        ),
        migrations.AddIndex(
            model_name='mistake',
            index=models.Index(fields=['enrollment', 'timestamp'], name='vocabulary__enrollm_bc4e36_idx'),
        ),
        migrations.AddIndex(
            model_name='mistake',
            index=models.Index(fields=['source'], name='vocabulary__source_65fe68_idx'),
        ),
    ]
