# Generated by Django 5.2.7 on 2025-10-22 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_topicprogress_highest_completed_order'),
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mistake',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistakes', to='languages.skill'),
        ),
        migrations.AddIndex(
            model_name='mistake',
            index=models.Index(fields=['skill', 'timestamp'], name='vocabulary__skill_i_5714f2_idx'),
        ),
    ]
