# Generated by Django 5.2.7 on 2025-11-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_mistake_skill_mistake_vocabulary__skill_i_5714f2_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordrelation',
            name='related',
        ),
        migrations.RemoveField(
            model_name='wordrelation',
            name='word',
        ),
        migrations.DeleteModel(
            name='AudioAsset',
        ),
        migrations.DeleteModel(
            name='WordRelation',
        ),
    ]
