# Generated by Django 5.2.6 on 2025-10-03 23:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_remove_userskillstats_uq_userskillstats_enrollment_skill_and_more'),
        ('vocabulary', '0002_learninginteraction_mistake_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='knownword',
            name='uq_knownword_enrollment_word',
        ),
        migrations.RemoveIndex(
            model_name='knownword',
            name='vocabulary__enrollm_3ee234_idx',
        ),
        migrations.AddField(
            model_name='knownword',
            name='correct_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knownword',
            name='ease_factor',
            field=models.FloatField(default=2.5, help_text='Ease factor (2.5 is default)'),
        ),
        migrations.AddField(
            model_name='knownword',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knownword',
            name='interval_days',
            field=models.IntegerField(default=1, help_text='Days until next review'),
        ),
        migrations.AddField(
            model_name='knownword',
            name='mastered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knownword',
            name='next_review',
            field=models.DateTimeField(blank=True, help_text='When to review next', null=True),
        ),
        migrations.AddField(
            model_name='knownword',
            name='repetitions',
            field=models.IntegerField(default=0, help_text='Number of successful repetitions'),
        ),
        migrations.AddField(
            model_name='knownword',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='knownword',
            name='times_forgotten',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knownword',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learninginteraction',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.word'),
        ),
        migrations.AddIndex(
            model_name='knownword',
            index=models.Index(fields=['enrollment', 'next_review'], name='vocabulary__enrollm_f6d89c_idx'),
        ),
        migrations.AddIndex(
            model_name='knownword',
            index=models.Index(fields=['enrollment', 'status'], name='vocabulary__enrollm_bab3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='knownword',
            index=models.Index(fields=['next_review'], name='vocabulary__next_re_74bbc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='knownword',
            constraint=models.UniqueConstraint(fields=('enrollment', 'word'), name='uq_knownword_enrollment_word_v2'),
        ),
    ]
