# Generated by Django 5.2.7 on 2025-10-17 20:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetUtterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('ipa', models.CharField(blank=True, default='', max_length=300)),
                ('language_code', models.CharField(default='en', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='PronunciationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_text', models.CharField(blank=True, default='', max_length=300)),
                ('language_code', models.CharField(default='en', max_length=16)),
                ('audio', models.FileField(upload_to='pron_attempts/')),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('words', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.conversation')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pron.targetutterance')),
            ],
        ),
    ]
