# Generated by Django 5.2.6 on 2025-09-30 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('enrollment_id', models.IntegerField()),
                ('lesson_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('enrollment_id', models.IntegerField()),
                ('prompt', models.TextField()),
                ('solution_translation', models.TextField(blank=True, null=True)),
                ('mispronounced_words', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('enrollment_id', models.IntegerField()),
                ('lesson_id', models.IntegerField(blank=True, null=True)),
                ('skill_id', models.IntegerField(blank=True, null=True)),
                ('word_id', models.IntegerField(blank=True, null=True)),
                ('priority_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('model_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_recommend.aimodelversion')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackLoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=50)),
                ('time_spent', models.IntegerField(default=0)),
                ('xp_gain', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ai_recommend.recommendation')),
            ],
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user_id', 'priority_score'], name='ai_recommen_user_id_82f241_idx'),
        ),
    ]
