# Generated by Django 5.2.6 on 2025-10-03 20:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spec', models.JSONField()),
                ('storage_path', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('dataset_snapshot', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.DeleteModel(
            name='LearningInteraction',
        ),
        migrations.DeleteModel(
            name='Mistake',
        ),
        migrations.AlterField(
            model_name='feedbackloop',
            name='outcome',
            field=models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='feedbackloop',
            index=models.Index(fields=['outcome', 'created_at'], name='ai_recommen_outcome_5f1d76_idx'),
        ),
        migrations.AddField(
            model_name='featuresnapshot',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_snapshots', to='ai_recommend.aimodelversion'),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to='ai_recommend.aimodelversion'),
        ),
    ]
