# Generated by Django 5.2.7 on 2025-10-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommend', '0002_featuresnapshot_trainingrun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrun',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='pending', max_length=20),
        ),
    ]
