# Generated by Django 5.2.7 on 2025-10-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommend', '0003_alter_trainingrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='rec_type',
            field=models.CharField(default='practice', max_length=20),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user_id', 'created_at'], name='ai_recommen_user_id_5bb5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['batch_id'], name='ai_recommen_batch_i_29d081_idx'),
        ),
    ]
