# Generated by Django 5.2.7 on 2025-10-17 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('native_name', models.CharField(blank=True, max_length=100)),
                ('direction', models.CharField(default='LTR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=10)),
                ('duration_seconds', models.IntegerField(default=120)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('listening', 'Listening'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('writing', 'Writing'), ('matching', 'Matching'), ('fillgap', 'Fill in the blanks'), ('ordering', 'Reorder words'), ('quiz', 'Generic MCQ/QA'), ('pron', 'Pronunciation')], default='quiz', max_length=32)),
                ('content', models.JSONField(blank=True, null=True)),
                ('xp_reward', models.IntegerField(default=10)),
                ('duration_seconds', models.IntegerField(default=90)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('golden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('xp', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('reviewable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkillStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('total_lessons_completed', models.IntegerField(default=0)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('proficiency_score', models.FloatField(default=0.0)),
                ('level', models.IntegerField(default=0, help_text='Crown level 0-5')),
                ('lessons_completed_at_level', models.IntegerField(default=0, help_text='Lessons completed at current level')),
                ('lessons_required_for_next', models.IntegerField(default=5, help_text='Lessons needed to level up')),
                ('needs_review', models.BooleanField(default=False)),
                ('review_reminder_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('mastered', 'Mastered')], default='locked', max_length=20)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('first_completed_at', models.DateTimeField(blank=True, null=True)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('total_xp', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='languages.language')),
            ],
        ),
    ]
