# Generated by Django 5.2.7 on 2025-10-17 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='languageenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonskill',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.lesson'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['type'], name='languages_s_type_e765b9_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['language_code'], name='languages_s_languag_d998cf_idx'),
        ),
        migrations.AddField(
            model_name='lessonskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.skill'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='skills',
            field=models.ManyToManyField(related_name='lessons', through='languages.LessonSkill', to='languages.skill'),
        ),
        migrations.AddField(
            model_name='topic',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='languages.language'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='languages.topic'),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='languages.languageenrollment'),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.topic'),
        ),
        migrations.AddField(
            model_name='userskillstats',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_stats', to='languages.languageenrollment'),
        ),
        migrations.AddField(
            model_name='userskillstats',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.skill'),
        ),
        migrations.AddIndex(
            model_name='languageenrollment',
            index=models.Index(fields=['user', 'language'], name='languages_l_user_id_93f141_idx'),
        ),
        migrations.AddConstraint(
            model_name='languageenrollment',
            constraint=models.UniqueConstraint(fields=('user', 'language'), name='uq_enrollment_user_language'),
        ),
        migrations.AddIndex(
            model_name='lessonskill',
            index=models.Index(fields=['lesson', 'order'], name='languages_l_lesson__e2d082_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonskill',
            index=models.Index(fields=['skill', 'order'], name='languages_l_skill_i_d25cb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonskill',
            unique_together={('lesson', 'skill')},
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['language', 'order'], name='languages_t_languag_da5eb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('language', 'slug'), name='uq_topic_language_slug'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['topic', 'order'], name='languages_l_topic_i_74cb76_idx'),
        ),
        migrations.AddIndex(
            model_name='topicprogress',
            index=models.Index(fields=['enrollment', 'completed', 'reviewable'], name='languages_t_enrollm_723de1_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'topic'), name='uq_topicprogress_enrollment_topic'),
        ),
        migrations.AddIndex(
            model_name='userskillstats',
            index=models.Index(fields=['enrollment', 'skill'], name='languages_u_enrollm_9122e5_idx'),
        ),
        migrations.AddIndex(
            model_name='userskillstats',
            index=models.Index(fields=['enrollment', 'level'], name='languages_u_enrollm_5ee38f_idx'),
        ),
        migrations.AddIndex(
            model_name='userskillstats',
            index=models.Index(fields=['needs_review', 'review_reminder_date'], name='languages_u_needs_r_ec84a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='userskillstats',
            constraint=models.UniqueConstraint(fields=('enrollment', 'skill'), name='uq_userskillstats_enrollment_skill_v2'),
        ),
    ]
