# Generated by Django 5.2.6 on 2025-09-29 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='languageenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='languages.skill'),
        ),
        migrations.AddField(
            model_name='suggestedlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.lesson'),
        ),
        migrations.AddField(
            model_name='suggestedlesson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='languages.language'),
        ),
        migrations.AddField(
            model_name='skill',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='languages.topic'),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='languages.languageenrollment'),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.topic'),
        ),
        migrations.AddField(
            model_name='userskillstats',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_stats', to='languages.languageenrollment'),
        ),
        migrations.AddField(
            model_name='userskillstats',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='languageenrollment',
            unique_together={('user', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='suggestedlesson',
            unique_together={('user', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('language', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='topicprogress',
            unique_together={('enrollment', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='userskillstats',
            unique_together={('enrollment', 'skill')},
        ),
    ]
