# Generated by Django 5.2.6 on 2025-10-03 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='suggestedlesson',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='suggestedlesson',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='suggestedlesson',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='languageenrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topicprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userskillstats',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='languageenrollment',
            index=models.Index(fields=['user', 'language'], name='languages_l_user_id_93f141_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['topic', 'order'], name='languages_s_topic_i_9055e0_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['language', 'order'], name='languages_t_languag_da5eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='topicprogress',
            index=models.Index(fields=['enrollment', 'completed', 'reviewable'], name='languages_t_enrollm_723de1_idx'),
        ),
        migrations.AddIndex(
            model_name='userskillstats',
            index=models.Index(fields=['enrollment', 'skill'], name='languages_u_enrollm_9122e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='languageenrollment',
            constraint=models.UniqueConstraint(fields=('user', 'language'), name='uq_enrollment_user_language'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('language', 'slug'), name='uq_topic_language_slug'),
        ),
        migrations.AddConstraint(
            model_name='topicprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'topic'), name='uq_topicprogress_enrollment_topic'),
        ),
        migrations.AddConstraint(
            model_name='userskillstats',
            constraint=models.UniqueConstraint(fields=('enrollment', 'skill'), name='uq_userskillstats_enrollment_skill'),
        ),
        migrations.DeleteModel(
            name='SuggestedLesson',
        ),
    ]
