# Generated by Django 5.2.7 on 2025-10-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_topic_embedding_topic_embedding_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='highest_completed_order',
            field=models.IntegerField(default=0),
        ),
    ]
