# Generated by Django 5.2.6 on 2025-10-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_alter_suggestedlesson_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userskillstats',
            name='uq_userskillstats_enrollment_skill',
        ),
        migrations.AddField(
            model_name='userskillstats',
            name='first_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userskillstats',
            name='lessons_completed_at_level',
            field=models.IntegerField(default=0, help_text='Lessons completed at current level'),
        ),
        migrations.AddField(
            model_name='userskillstats',
            name='lessons_required_for_next',
            field=models.IntegerField(default=5, help_text='Lessons needed to level up'),
        ),
        migrations.AddField(
            model_name='userskillstats',
            name='level',
            field=models.IntegerField(default=0, help_text='Crown level 0-5'),
        ),
        migrations.AddField(
            model_name='userskillstats',
            name='mastered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userskillstats',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userskillstats',
            name='review_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userskillstats',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('mastered', 'Mastered')], default='locked', max_length=20),
        ),
        migrations.AddField(
            model_name='userskillstats',
            name='total_lessons_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userskillstats',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='userskillstats',
            index=models.Index(fields=['enrollment', 'level'], name='languages_u_enrollm_5ee38f_idx'),
        ),
        migrations.AddIndex(
            model_name='userskillstats',
            index=models.Index(fields=['needs_review', 'review_reminder_date'], name='languages_u_needs_r_ec84a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='userskillstats',
            constraint=models.UniqueConstraint(fields=('enrollment', 'skill'), name='uq_userskillstats_enrollment_skill_v2'),
        ),
    ]
