# Generated by Django 5.2.7 on 2025-10-22 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_topicprogress_highest_completed_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='content',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='slug',
        ),
        migrations.CreateModel(
            name='ListeningPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('question_text', models.CharField(blank=True, max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_prompts', to='languages.skill')),
            ],
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.CharField(max_length=255)),
                ('right_text', models.CharField(max_length=255)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='languages.skill')),
            ],
        ),
        migrations.CreateModel(
            name='OrderingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order_index', models.IntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_items', to='languages.skill')),
            ],
        ),
        migrations.CreateModel(
            name='PronunciationPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('phonemes', models.CharField(blank=True, max_length=100)),
                ('answer', models.CharField(blank=True, max_length=100)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_prompts', to='languages.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage', models.TextField()),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_content', to='languages.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_questions', to='languages.skill')),
            ],
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fillgaps', to='languages.skill')),
            ],
        ),
        migrations.CreateModel(
            name='SkillQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='languages.skill')),
            ],
        ),
        migrations.CreateModel(
            name='SkillChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='languages.skillquestion')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('tip', models.CharField(blank=True, max_length=255)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_prompts', to='languages.skill')),
            ],
        ),
        migrations.CreateModel(
            name='WritingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_questions', to='languages.skill')),
            ],
        ),
    ]
