# Generated by Django 5.2.7 on 2025-10-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_remove_skill_content_remove_skill_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scenarioskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scenarioskill',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='scenarioskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='roleplayscenario',
            name='skills',
        ),
        migrations.AlterModelOptions(
            name='roleplayscenario',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='roleplayscenario',
            name='uq_roleplay_topic_slug',
        ),
        migrations.RemoveIndex(
            model_name='roleplayscenario',
            name='languages_r_topic_i_f550dd_idx',
        ),
        migrations.RemoveField(
            model_name='roleplayscenario',
            name='topic',
        ),
        migrations.AddField(
            model_name='roleplayscenario',
            name='skill_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='roleplayscenario',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name='roleplayscenario',
            index=models.Index(fields=['order'], name='languages_r_order_91edfc_idx'),
        ),
        migrations.DeleteModel(
            name='ScenarioSkill',
        ),
    ]
