# Generated by Django 5.2.7 on 2025-10-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0007_alter_roleplayblock_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleplayblock',
            name='embedding_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='roleplayblock',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='roleplayscenario',
            name='embedding_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='roleplayscenario',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='embedding_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='topic',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
