# Generated by Django 5.2.7 on 2025-10-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0008_roleplayblock_embedding_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleplayblock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
