# Generated by Django 5.2.7 on 2025-10-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0009_roleplayblock_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingpair',
            name='left_text_i18n',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='skill',
            name='title_i18n',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='skillquestion',
            name='question_text_i18n',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
