# Generated by Django 5.2.7 on 2025-11-13 19:06

import languages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0010_matchingpair_left_text_i18n_skill_description_i18n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronunciationprompt',
            name='tts_duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pronunciationprompt',
            name='tts_file',
            field=models.FileField(blank=True, null=True, upload_to=languages.models.pron_upload_to),
        ),
        migrations.AddField(
            model_name='pronunciationprompt',
            name='tts_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pronunciationprompt',
            name='tts_mime',
            field=models.CharField(default='audio/mpeg', max_length=64),
        ),
        migrations.AddField(
            model_name='pronunciationprompt',
            name='tts_provider',
            field=models.CharField(default='piper', max_length=20),
        ),
        migrations.AddField(
            model_name='pronunciationprompt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
