# Generated by Django 5.2.7 on 2025-10-17 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='languages.topic'),
        ),
        migrations.AddField(
            model_name='turn',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='chat.conversation'),
        ),
    ]
