# Generated by Django 5.2.6 on 2025-10-04 03:50

import django.contrib.auth.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_conversation_user_alter_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name=django.contrib.auth.models.User),
        ),
    ]
