# Generated by Django 5.2.6 on 2025-10-06 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_conversation_id'),
        ('languages', '0004_remove_userskillstats_uq_userskillstats_enrollment_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.topic'),
        ),
        migrations.AlterField(
            model_name='topicscript',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='languages.topic'),
        ),
        migrations.AlterField(
            model_name='topicknowledge',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='languages.topic'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
